name: ServerEssentials
main: NoUser123098\ServerEssentials\main
version: 0.0.1
author: NoUser123098
api: [3.0.0]
load: POSTWORLD
commands:
  makerank:
    permission: serveressentials.command.makerank
    description: "Creates a rank."
    usage: "/makerank <name> <format>"
  setrank:
    permission: serveressentials.command.setrank
    description: "Sets a player's rank."
    usage: "/setrank <player>"
  setppermission:
    permission: serveressentials.command.setppermission
    description: "Sets a permission for a player."
    usage: "/setppermission <player> <permission>"
  setgpermission:
    permission: serveressentials.command.setgpermission
    description: "Sets a permission for a group."
    usage: "/setgpermission <group> <permission>"
  balance:
    permission: serveressentials.command.balance
    description: "Checks your balance."
    usage: "/balance"
  givemoney:
    permission: serveressentials.command.givemoney
    description: "Gives a player an amount of money."
    usage: "/givemoney <player> <amount>"
  setmoney:
    permission: serveressentials.command.setmoney
    description: "Sets a player's amount of money."
    usage: "/setmoney <player> <amount>"
  makemine:
    permission: serveressentials.command.makemine
    description: "Sets an area as a prison mine."
    usage: "/makemine <name>"
  setmine:
    permission: serveressentials.command.setmine
    description: "Sets the blocks a mine will contain."
    usage: "/setmine <name> <id> <percent> etc..."
  resetmine:
    permission: serveressentials.command.resetmine
    description: "Resets a mine."
    usage: "/resetmine <name>"
  resetallmines:
    permission: serveressentials.command.resetallmines
    description: "Resets all mines."
    usage: "/resetallmines"
  protectedarea:
    permission: serveressentials.command.protectarea
    description: "Protect an area."
    usage: "/protectedarea <pos1> <pos2> <name>"
  delprotected:
    permission: serveressentials.command.deleteprotectedarea
    description: "Delete an area's protection."
    usage: "/delprotected <name>"
