name: ServerEssentials
main: NoUser123098\ServerEssentials\main
version: 0.0.1
author: NoUser123098
api: [3.0.0]
load: POSTWORLD
commands:
  makerank:
    permission: serveressentials.command.makerank
    description: "Creates a rank."
    usage: "/makerank <name> <format>"
  setrank:
    permission: serveressentials.command.setrank
    description: "Sets a player's rank."
    usage: "/setrank <player>"
  setppermission:
    permission: serveressentials.command.setppermission
    description: "Sets a permission for a player."
    usage: "/setppermission <player> <permission>"
  setgpermission:
    permission: serveressentials.command.setgpermission
    description: "Sets a permission for a group."
    usage: "/setgpermission <group> <permission>"
